{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "ename": "OperationalError",
     "evalue": "(psycopg2.OperationalError) could not translate host name \"postgres\" to address: Unknown host\n\n(Background on this error at: https://sqlalche.me/e/14/e3q8)",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3256\u001b[0m, in \u001b[0;36mEngine._wrap_pool_connect\u001b[1;34m(self, fn, connection)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3254'>3255</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m-> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3255'>3256</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m fn()\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3256'>3257</a>\u001b[0m \u001b[39mexcept\u001b[39;00m dialect\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mError \u001b[39mas\u001b[39;00m e:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:310\u001b[0m, in \u001b[0;36mPool.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=302'>303</a>\u001b[0m \u001b[39m\"\"\"Return a DBAPI connection from the pool.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=303'>304</a>\u001b[0m \n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=304'>305</a>\u001b[0m \u001b[39mThe connection is instrumented such that when its\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=307'>308</a>\u001b[0m \n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=308'>309</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=309'>310</a>\u001b[0m \u001b[39mreturn\u001b[39;00m _ConnectionFairy\u001b[39m.\u001b[39;49m_checkout(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:868\u001b[0m, in \u001b[0;36m_ConnectionFairy._checkout\u001b[1;34m(cls, pool, threadconns, fairy)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=866'>867</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m fairy:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=867'>868</a>\u001b[0m     fairy \u001b[39m=\u001b[39m _ConnectionRecord\u001b[39m.\u001b[39;49mcheckout(pool)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=869'>870</a>\u001b[0m     fairy\u001b[39m.\u001b[39m_pool \u001b[39m=\u001b[39m pool\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:476\u001b[0m, in \u001b[0;36m_ConnectionRecord.checkout\u001b[1;34m(cls, pool)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=473'>474</a>\u001b[0m \u001b[39m@classmethod\u001b[39m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=474'>475</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mcheckout\u001b[39m(\u001b[39mcls\u001b[39m, pool):\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=475'>476</a>\u001b[0m     rec \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_do_get()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=476'>477</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:145\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=143'>144</a>\u001b[0m \u001b[39mexcept\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=144'>145</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=145'>146</a>\u001b[0m         \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_dec_overflow()\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:143\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=141'>142</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=142'>143</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_create_connection()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=143'>144</a>\u001b[0m \u001b[39mexcept\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:256\u001b[0m, in \u001b[0;36mPool._create_connection\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=253'>254</a>\u001b[0m \u001b[39m\"\"\"Called by subclasses to create a new ConnectionRecord.\"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=255'>256</a>\u001b[0m \u001b[39mreturn\u001b[39;00m _ConnectionRecord(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:371\u001b[0m, in \u001b[0;36m_ConnectionRecord.__init__\u001b[1;34m(self, pool, connect)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=369'>370</a>\u001b[0m \u001b[39mif\u001b[39;00m connect:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=370'>371</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__connect()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=371'>372</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfinalize_callback \u001b[39m=\u001b[39m deque()\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:665\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=663'>664</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=664'>665</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=665'>666</a>\u001b[0m         pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mError on connect(): \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, e)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:661\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=659'>660</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstarttime \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=660'>661</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi_connection \u001b[39m=\u001b[39m connection \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_invoke_creator(\u001b[39mself\u001b[39;49m)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=661'>662</a>\u001b[0m pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mCreated new connection \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m\"\u001b[39m, connection)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\create.py:590\u001b[0m, in \u001b[0;36mcreate_engine.<locals>.connect\u001b[1;34m(connection_record)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/create.py?line=588'>589</a>\u001b[0m             \u001b[39mreturn\u001b[39;00m connection\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/create.py?line=589'>590</a>\u001b[0m \u001b[39mreturn\u001b[39;00m dialect\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\default.py:597\u001b[0m, in \u001b[0;36mDefaultDialect.connect\u001b[1;34m(self, *cargs, **cparams)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/default.py?line=594'>595</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m, \u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams):\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/default.py?line=595'>596</a>\u001b[0m     \u001b[39m# inherits the docstring from interfaces.Dialect.connect\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/default.py?line=596'>597</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\psycopg2\\__init__.py:122\u001b[0m, in \u001b[0;36mconnect\u001b[1;34m(dsn, connection_factory, cursor_factory, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=120'>121</a>\u001b[0m dsn \u001b[39m=\u001b[39m _ext\u001b[39m.\u001b[39mmake_dsn(dsn, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=121'>122</a>\u001b[0m conn \u001b[39m=\u001b[39m _connect(dsn, connection_factory\u001b[39m=\u001b[39mconnection_factory, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwasync)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=122'>123</a>\u001b[0m \u001b[39mif\u001b[39;00m cursor_factory \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "\u001b[1;31mOperationalError\u001b[0m: could not translate host name \"postgres\" to address: Unknown host\n",
      "\nThe above exception was the direct cause of the following exception:\n",
      "\u001b[1;31mOperationalError\u001b[0m                          Traceback (most recent call last)",
      "\u001b[1;32mc:\\Users\\PC Paul\\Downloads\\DataEngOwnProject\\app_dash\\test.ipynb Cell 1'\u001b[0m in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/PC%20Paul/Downloads/DataEngOwnProject/app_dash/test.ipynb#ch0000000?line=14'>15</a>\u001b[0m table_target_prediction \u001b[39m=\u001b[39m configurations\u001b[39m.\u001b[39mparams[\u001b[39m\"\u001b[39m\u001b[39mdb_target_prediction_table\u001b[39m\u001b[39m\"\u001b[39m] \n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/PC%20Paul/Downloads/DataEngOwnProject/app_dash/test.ipynb#ch0000000?line=16'>17</a>\u001b[0m engine \u001b[39m=\u001b[39m create_engine(db_engine)\n\u001b[1;32m---> <a href='vscode-notebook-cell:/c%3A/Users/PC%20Paul/Downloads/DataEngOwnProject/app_dash/test.ipynb#ch0000000?line=17'>18</a>\u001b[0m results_from_db \u001b[39m=\u001b[39m pd\u001b[39m.\u001b[39;49mread_sql_table(\u001b[39m'\u001b[39;49m\u001b[39mresults\u001b[39;49m\u001b[39m'\u001b[39;49m, con \u001b[39m=\u001b[39;49m engine)\n\u001b[0;32m     <a href='vscode-notebook-cell:/c%3A/Users/PC%20Paul/Downloads/DataEngOwnProject/app_dash/test.ipynb#ch0000000?line=18'>19</a>\u001b[0m target_prediction_from_db \u001b[39m=\u001b[39m pd\u001b[39m.\u001b[39mread_sql_table(\u001b[39m'\u001b[39m\u001b[39mtarget_prediction\u001b[39m\u001b[39m'\u001b[39m, con \u001b[39m=\u001b[39m engine)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\pandas\\io\\sql.py:285\u001b[0m, in \u001b[0;36mread_sql_table\u001b[1;34m(table_name, con, schema, index_col, coerce_float, parse_dates, columns, chunksize)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=228'>229</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=229'>230</a>\u001b[0m \u001b[39mRead SQL database table into a DataFrame.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=230'>231</a>\u001b[0m \n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=281'>282</a>\u001b[0m \u001b[39m>>> pd.read_sql_table('table_name', 'postgres:///db_name')  # doctest:+SKIP\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=282'>283</a>\u001b[0m \u001b[39m\"\"\"\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=283'>284</a>\u001b[0m pandas_sql \u001b[39m=\u001b[39m pandasSQL_builder(con, schema\u001b[39m=\u001b[39mschema)\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=284'>285</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m pandas_sql\u001b[39m.\u001b[39;49mhas_table(table_name):\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=285'>286</a>\u001b[0m     \u001b[39mraise\u001b[39;00m \u001b[39mValueError\u001b[39;00m(\u001b[39mf\u001b[39m\u001b[39m\"\u001b[39m\u001b[39mTable \u001b[39m\u001b[39m{\u001b[39;00mtable_name\u001b[39m}\u001b[39;00m\u001b[39m not found\u001b[39m\u001b[39m\"\u001b[39m)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=287'>288</a>\u001b[0m table \u001b[39m=\u001b[39m pandas_sql\u001b[39m.\u001b[39mread_table(\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=288'>289</a>\u001b[0m     table_name,\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=289'>290</a>\u001b[0m     index_col\u001b[39m=\u001b[39mindex_col,\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=293'>294</a>\u001b[0m     chunksize\u001b[39m=\u001b[39mchunksize,\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=294'>295</a>\u001b[0m )\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\pandas\\io\\sql.py:1759\u001b[0m, in \u001b[0;36mSQLDatabase.has_table\u001b[1;34m(self, name, schema)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=1755'>1756</a>\u001b[0m \u001b[39mif\u001b[39;00m _gt14():\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=1756'>1757</a>\u001b[0m     \u001b[39mfrom\u001b[39;00m \u001b[39msqlalchemy\u001b[39;00m \u001b[39mimport\u001b[39;00m inspect\n\u001b[1;32m-> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=1758'>1759</a>\u001b[0m     insp \u001b[39m=\u001b[39m inspect(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mconnectable)\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=1759'>1760</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m insp\u001b[39m.\u001b[39mhas_table(name, schema \u001b[39mor\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mmeta\u001b[39m.\u001b[39mschema)\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/pandas/io/sql.py?line=1760'>1761</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\inspection.py:64\u001b[0m, in \u001b[0;36minspect\u001b[1;34m(subject, raiseerr)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/inspection.py?line=61'>62</a>\u001b[0m \u001b[39mif\u001b[39;00m reg \u001b[39mis\u001b[39;00m \u001b[39mTrue\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/inspection.py?line=62'>63</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m subject\n\u001b[1;32m---> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/inspection.py?line=63'>64</a>\u001b[0m ret \u001b[39m=\u001b[39m reg(subject)\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/inspection.py?line=64'>65</a>\u001b[0m \u001b[39mif\u001b[39;00m ret \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/inspection.py?line=65'>66</a>\u001b[0m     \u001b[39mbreak\u001b[39;00m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\reflection.py:182\u001b[0m, in \u001b[0;36mInspector._engine_insp\u001b[1;34m(bind)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=179'>180</a>\u001b[0m \u001b[39m@inspection\u001b[39m\u001b[39m.\u001b[39m_inspects(Engine)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=180'>181</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_engine_insp\u001b[39m(bind):\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=181'>182</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m Inspector\u001b[39m.\u001b[39;49m_construct(Inspector\u001b[39m.\u001b[39;49m_init_engine, bind)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\reflection.py:117\u001b[0m, in \u001b[0;36mInspector._construct\u001b[1;34m(cls, init, bind)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=113'>114</a>\u001b[0m     \u001b[39mcls\u001b[39m \u001b[39m=\u001b[39m bind\u001b[39m.\u001b[39mdialect\u001b[39m.\u001b[39minspector\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=115'>116</a>\u001b[0m \u001b[39mself\u001b[39m \u001b[39m=\u001b[39m \u001b[39mcls\u001b[39m\u001b[39m.\u001b[39m\u001b[39m__new__\u001b[39m(\u001b[39mcls\u001b[39m)\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=116'>117</a>\u001b[0m init(\u001b[39mself\u001b[39;49m, bind)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=117'>118</a>\u001b[0m \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\reflection.py:128\u001b[0m, in \u001b[0;36mInspector._init_engine\u001b[1;34m(self, engine)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=125'>126</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_init_engine\u001b[39m(\u001b[39mself\u001b[39m, engine):\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=126'>127</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mbind \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine \u001b[39m=\u001b[39m engine\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=127'>128</a>\u001b[0m     engine\u001b[39m.\u001b[39;49mconnect()\u001b[39m.\u001b[39mclose()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=128'>129</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_op_context_requires_connect \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/reflection.py?line=129'>130</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mengine\u001b[39m.\u001b[39mdialect\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3210\u001b[0m, in \u001b[0;36mEngine.connect\u001b[1;34m(self, close_with_result)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3194'>3195</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m, close_with_result\u001b[39m=\u001b[39m\u001b[39mFalse\u001b[39;00m):\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3195'>3196</a>\u001b[0m     \u001b[39m\"\"\"Return a new :class:`_engine.Connection` object.\u001b[39;00m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3196'>3197</a>\u001b[0m \n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3197'>3198</a>\u001b[0m \u001b[39m    The :class:`_engine.Connection` object is a facade that uses a DBAPI\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3206'>3207</a>\u001b[0m \n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3207'>3208</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3209'>3210</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_connection_cls(\u001b[39mself\u001b[39;49m, close_with_result\u001b[39m=\u001b[39;49mclose_with_result)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:96\u001b[0m, in \u001b[0;36mConnection.__init__\u001b[1;34m(self, engine, connection, close_with_result, _branch_from, _execution_options, _dispatch, _has_events, _allow_revalidate)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=90'>91</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_has_events \u001b[39m=\u001b[39m _branch_from\u001b[39m.\u001b[39m_has_events\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=91'>92</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=92'>93</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_dbapi_connection \u001b[39m=\u001b[39m (\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=93'>94</a>\u001b[0m         connection\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=94'>95</a>\u001b[0m         \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m\n\u001b[1;32m---> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=95'>96</a>\u001b[0m         \u001b[39melse\u001b[39;00m engine\u001b[39m.\u001b[39;49mraw_connection()\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=96'>97</a>\u001b[0m     )\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=98'>99</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_transaction \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_nested_transaction \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=99'>100</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__savepoint_seq \u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3289\u001b[0m, in \u001b[0;36mEngine.raw_connection\u001b[1;34m(self, _connection)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3266'>3267</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mraw_connection\u001b[39m(\u001b[39mself\u001b[39m, _connection\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3267'>3268</a>\u001b[0m     \u001b[39m\"\"\"Return a \"raw\" DBAPI connection from the connection pool.\u001b[39;00m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3268'>3269</a>\u001b[0m \n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3269'>3270</a>\u001b[0m \u001b[39m    The returned object is a proxied version of the DBAPI\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3286'>3287</a>\u001b[0m \n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3287'>3288</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m-> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3288'>3289</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_wrap_pool_connect(\u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49mpool\u001b[39m.\u001b[39;49mconnect, _connection)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3259\u001b[0m, in \u001b[0;36mEngine._wrap_pool_connect\u001b[1;34m(self, fn, connection)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3256'>3257</a>\u001b[0m \u001b[39mexcept\u001b[39;00m dialect\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3257'>3258</a>\u001b[0m     \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[1;32m-> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3258'>3259</a>\u001b[0m         Connection\u001b[39m.\u001b[39;49m_handle_dbapi_exception_noconnection(\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3259'>3260</a>\u001b[0m             e, dialect, \u001b[39mself\u001b[39;49m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3260'>3261</a>\u001b[0m         )\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3261'>3262</a>\u001b[0m     \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3262'>3263</a>\u001b[0m         util\u001b[39m.\u001b[39mraise_(\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3263'>3264</a>\u001b[0m             sys\u001b[39m.\u001b[39mexc_info()[\u001b[39m1\u001b[39m], with_traceback\u001b[39m=\u001b[39msys\u001b[39m.\u001b[39mexc_info()[\u001b[39m2\u001b[39m]\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3264'>3265</a>\u001b[0m         )\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:2106\u001b[0m, in \u001b[0;36mConnection._handle_dbapi_exception_noconnection\u001b[1;34m(cls, e, dialect, engine)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=2103'>2104</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(newraise, with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m], from_\u001b[39m=\u001b[39me)\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=2104'>2105</a>\u001b[0m \u001b[39melif\u001b[39;00m should_wrap:\n\u001b[1;32m-> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=2105'>2106</a>\u001b[0m     util\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=2106'>2107</a>\u001b[0m         sqlalchemy_exception, with_traceback\u001b[39m=\u001b[39;49mexc_info[\u001b[39m2\u001b[39;49m], from_\u001b[39m=\u001b[39;49me\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=2107'>2108</a>\u001b[0m     )\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=2108'>2109</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=2109'>2110</a>\u001b[0m     util\u001b[39m.\u001b[39mraise_(exc_info[\u001b[39m1\u001b[39m], with_traceback\u001b[39m=\u001b[39mexc_info[\u001b[39m2\u001b[39m])\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=203'>204</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\base.py:3256\u001b[0m, in \u001b[0;36mEngine._wrap_pool_connect\u001b[1;34m(self, fn, connection)\u001b[0m\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3253'>3254</a>\u001b[0m dialect \u001b[39m=\u001b[39m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdialect\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3254'>3255</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m-> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3255'>3256</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m fn()\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3256'>3257</a>\u001b[0m \u001b[39mexcept\u001b[39;00m dialect\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mError \u001b[39mas\u001b[39;00m e:\n\u001b[0;32m   <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/base.py?line=3257'>3258</a>\u001b[0m     \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:310\u001b[0m, in \u001b[0;36mPool.connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=301'>302</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=302'>303</a>\u001b[0m     \u001b[39m\"\"\"Return a DBAPI connection from the pool.\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=303'>304</a>\u001b[0m \n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=304'>305</a>\u001b[0m \u001b[39m    The connection is instrumented such that when its\u001b[39;00m\n\u001b[1;32m   (...)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=307'>308</a>\u001b[0m \n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=308'>309</a>\u001b[0m \u001b[39m    \"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=309'>310</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m _ConnectionFairy\u001b[39m.\u001b[39;49m_checkout(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:868\u001b[0m, in \u001b[0;36m_ConnectionFairy._checkout\u001b[1;34m(cls, pool, threadconns, fairy)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=864'>865</a>\u001b[0m \u001b[39m@classmethod\u001b[39m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=865'>866</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_checkout\u001b[39m(\u001b[39mcls\u001b[39m, pool, threadconns\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m, fairy\u001b[39m=\u001b[39m\u001b[39mNone\u001b[39;00m):\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=866'>867</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m fairy:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=867'>868</a>\u001b[0m         fairy \u001b[39m=\u001b[39m _ConnectionRecord\u001b[39m.\u001b[39;49mcheckout(pool)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=869'>870</a>\u001b[0m         fairy\u001b[39m.\u001b[39m_pool \u001b[39m=\u001b[39m pool\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=870'>871</a>\u001b[0m         fairy\u001b[39m.\u001b[39m_counter \u001b[39m=\u001b[39m \u001b[39m0\u001b[39m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:476\u001b[0m, in \u001b[0;36m_ConnectionRecord.checkout\u001b[1;34m(cls, pool)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=473'>474</a>\u001b[0m \u001b[39m@classmethod\u001b[39m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=474'>475</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mcheckout\u001b[39m(\u001b[39mcls\u001b[39m, pool):\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=475'>476</a>\u001b[0m     rec \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_do_get()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=476'>477</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=477'>478</a>\u001b[0m         dbapi_connection \u001b[39m=\u001b[39m rec\u001b[39m.\u001b[39mget_connection()\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:145\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=142'>143</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_create_connection()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=143'>144</a>\u001b[0m     \u001b[39mexcept\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=144'>145</a>\u001b[0m         \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=145'>146</a>\u001b[0m             \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_dec_overflow()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=146'>147</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=67'>68</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=74'>75</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m compat\u001b[39m.\u001b[39mpy3k \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m]:\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=75'>76</a>\u001b[0m         \u001b[39m# emulate Py3K's behavior of telling us when an exception\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=76'>77</a>\u001b[0m         \u001b[39m# occurs in an exception handler.\u001b[39;00m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=203'>204</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\impl.py:143\u001b[0m, in \u001b[0;36mQueuePool._do_get\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=140'>141</a>\u001b[0m \u001b[39mif\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_inc_overflow():\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=141'>142</a>\u001b[0m     \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=142'>143</a>\u001b[0m         \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m_create_connection()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=143'>144</a>\u001b[0m     \u001b[39mexcept\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/impl.py?line=144'>145</a>\u001b[0m         \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:256\u001b[0m, in \u001b[0;36mPool._create_connection\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=252'>253</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39m_create_connection\u001b[39m(\u001b[39mself\u001b[39m):\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=253'>254</a>\u001b[0m     \u001b[39m\"\"\"Called by subclasses to create a new ConnectionRecord.\"\"\"\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=255'>256</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m _ConnectionRecord(\u001b[39mself\u001b[39;49m)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:371\u001b[0m, in \u001b[0;36m_ConnectionRecord.__init__\u001b[1;34m(self, pool, connect)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=368'>369</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m__pool \u001b[39m=\u001b[39m pool\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=369'>370</a>\u001b[0m \u001b[39mif\u001b[39;00m connect:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=370'>371</a>\u001b[0m     \u001b[39mself\u001b[39;49m\u001b[39m.\u001b[39;49m__connect()\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=371'>372</a>\u001b[0m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfinalize_callback \u001b[39m=\u001b[39m deque()\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:665\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=662'>663</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfresh \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=663'>664</a>\u001b[0m \u001b[39mexcept\u001b[39;00m \u001b[39mException\u001b[39;00m \u001b[39mas\u001b[39;00m e:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=664'>665</a>\u001b[0m     \u001b[39mwith\u001b[39;00m util\u001b[39m.\u001b[39msafe_reraise():\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=665'>666</a>\u001b[0m         pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mError on connect(): \u001b[39m\u001b[39m%s\u001b[39;00m\u001b[39m\"\u001b[39m, e)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=666'>667</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=667'>668</a>\u001b[0m     \u001b[39m# in SQLAlchemy 1.4 the first_connect event is not used by\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=668'>669</a>\u001b[0m     \u001b[39m# the engine, so this will usually not be set\u001b[39;00m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\langhelpers.py:70\u001b[0m, in \u001b[0;36msafe_reraise.__exit__\u001b[1;34m(self, type_, value, traceback)\u001b[0m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=67'>68</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39m=\u001b[39m \u001b[39mNone\u001b[39;00m  \u001b[39m# remove potential circular references\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=68'>69</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mwarn_only:\n\u001b[1;32m---> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=69'>70</a>\u001b[0m         compat\u001b[39m.\u001b[39;49mraise_(\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=70'>71</a>\u001b[0m             exc_value,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=71'>72</a>\u001b[0m             with_traceback\u001b[39m=\u001b[39;49mexc_tb,\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=72'>73</a>\u001b[0m         )\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=73'>74</a>\u001b[0m \u001b[39melse\u001b[39;00m:\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=74'>75</a>\u001b[0m     \u001b[39mif\u001b[39;00m \u001b[39mnot\u001b[39;00m compat\u001b[39m.\u001b[39mpy3k \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info \u001b[39mand\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39m_exc_info[\u001b[39m1\u001b[39m]:\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=75'>76</a>\u001b[0m         \u001b[39m# emulate Py3K's behavior of telling us when an exception\u001b[39;00m\n\u001b[0;32m     <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/langhelpers.py?line=76'>77</a>\u001b[0m         \u001b[39m# occurs in an exception handler.\u001b[39;00m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\util\\compat.py:207\u001b[0m, in \u001b[0;36mraise_\u001b[1;34m(***failed resolving arguments***)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=203'>204</a>\u001b[0m     exception\u001b[39m.\u001b[39m__cause__ \u001b[39m=\u001b[39m replace_context\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=205'>206</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=206'>207</a>\u001b[0m     \u001b[39mraise\u001b[39;00m exception\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=207'>208</a>\u001b[0m \u001b[39mfinally\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=208'>209</a>\u001b[0m     \u001b[39m# credit to\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=209'>210</a>\u001b[0m     \u001b[39m# https://cosmicpercolator.com/2016/01/13/exception-leaks-in-python-2-and-3/\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=210'>211</a>\u001b[0m     \u001b[39m# as the __traceback__ object creates a cycle\u001b[39;00m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/util/compat.py?line=211'>212</a>\u001b[0m     \u001b[39mdel\u001b[39;00m exception, replace_context, from_, with_traceback\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\pool\\base.py:661\u001b[0m, in \u001b[0;36m_ConnectionRecord.__connect\u001b[1;34m(self)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=658'>659</a>\u001b[0m \u001b[39mtry\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=659'>660</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mstarttime \u001b[39m=\u001b[39m time\u001b[39m.\u001b[39mtime()\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=660'>661</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi_connection \u001b[39m=\u001b[39m connection \u001b[39m=\u001b[39m pool\u001b[39m.\u001b[39;49m_invoke_creator(\u001b[39mself\u001b[39;49m)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=661'>662</a>\u001b[0m     pool\u001b[39m.\u001b[39mlogger\u001b[39m.\u001b[39mdebug(\u001b[39m\"\u001b[39m\u001b[39mCreated new connection \u001b[39m\u001b[39m%r\u001b[39;00m\u001b[39m\"\u001b[39m, connection)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/pool/base.py?line=662'>663</a>\u001b[0m     \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mfresh \u001b[39m=\u001b[39m \u001b[39mTrue\u001b[39;00m\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\create.py:590\u001b[0m, in \u001b[0;36mcreate_engine.<locals>.connect\u001b[1;34m(connection_record)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/create.py?line=587'>588</a>\u001b[0m         \u001b[39mif\u001b[39;00m connection \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/create.py?line=588'>589</a>\u001b[0m             \u001b[39mreturn\u001b[39;00m connection\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/create.py?line=589'>590</a>\u001b[0m \u001b[39mreturn\u001b[39;00m dialect\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\sqlalchemy\\engine\\default.py:597\u001b[0m, in \u001b[0;36mDefaultDialect.connect\u001b[1;34m(self, *cargs, **cparams)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/default.py?line=594'>595</a>\u001b[0m \u001b[39mdef\u001b[39;00m \u001b[39mconnect\u001b[39m(\u001b[39mself\u001b[39m, \u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams):\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/default.py?line=595'>596</a>\u001b[0m     \u001b[39m# inherits the docstring from interfaces.Dialect.connect\u001b[39;00m\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/sqlalchemy/engine/default.py?line=596'>597</a>\u001b[0m     \u001b[39mreturn\u001b[39;00m \u001b[39mself\u001b[39m\u001b[39m.\u001b[39mdbapi\u001b[39m.\u001b[39mconnect(\u001b[39m*\u001b[39mcargs, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mcparams)\n",
      "File \u001b[1;32mC:\\ProgramData\\Anaconda3\\envs\\py310\\lib\\site-packages\\psycopg2\\__init__.py:122\u001b[0m, in \u001b[0;36mconnect\u001b[1;34m(dsn, connection_factory, cursor_factory, **kwargs)\u001b[0m\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=118'>119</a>\u001b[0m     kwasync[\u001b[39m'\u001b[39m\u001b[39masync_\u001b[39m\u001b[39m'\u001b[39m] \u001b[39m=\u001b[39m kwargs\u001b[39m.\u001b[39mpop(\u001b[39m'\u001b[39m\u001b[39masync_\u001b[39m\u001b[39m'\u001b[39m)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=120'>121</a>\u001b[0m dsn \u001b[39m=\u001b[39m _ext\u001b[39m.\u001b[39mmake_dsn(dsn, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwargs)\n\u001b[1;32m--> <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=121'>122</a>\u001b[0m conn \u001b[39m=\u001b[39m _connect(dsn, connection_factory\u001b[39m=\u001b[39mconnection_factory, \u001b[39m*\u001b[39m\u001b[39m*\u001b[39mkwasync)\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=122'>123</a>\u001b[0m \u001b[39mif\u001b[39;00m cursor_factory \u001b[39mis\u001b[39;00m \u001b[39mnot\u001b[39;00m \u001b[39mNone\u001b[39;00m:\n\u001b[0;32m    <a href='file:///c%3A/ProgramData/Anaconda3/envs/py310/lib/site-packages/psycopg2/__init__.py?line=123'>124</a>\u001b[0m     conn\u001b[39m.\u001b[39mcursor_factory \u001b[39m=\u001b[39m cursor_factory\n",
      "\u001b[1;31mOperationalError\u001b[0m: (psycopg2.OperationalError) could not translate host name \"postgres\" to address: Unknown host\n\n(Background on this error at: https://sqlalche.me/e/14/e3q8)"
     ]
    }
   ],
   "source": [
    "import dash\n",
    "import dash_bootstrap_components as dbc\n",
    "import dash_core_components as dcc\n",
    "import dash_html_components as html\n",
    "import flask\n",
    "\n",
    "import pandas as pd\n",
    "from sqlalchemy import create_engine\n",
    "import ml_pipeline_config_test as configurations #todo: find a better solution instead of this dupe file \n",
    "\n",
    "db_engine = configurations.params[\"db_engine\"]\n",
    "db_schema = configurations.params[\"db_schema\"]\n",
    "table_raw = configurations.params[\"db_raw_table\"] \n",
    "table_results = configurations.params[\"db_results_table\"]\n",
    "table_target_prediction = configurations.params[\"db_target_prediction_table\"] \n",
    "\n",
    "engine = create_engine(db_engine)\n",
    "results_from_db = pd.read_sql_table('results', con = engine)\n",
    "target_prediction_from_db = pd.read_sql_table('target_prediction', con = engine)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Collecting psycopg2\n",
      "  Downloading psycopg2-2.9.3-cp310-cp310-win_amd64.whl (1.2 MB)\n",
      "Installing collected packages: psycopg2\n",
      "Successfully installed psycopg2-2.9.3\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "interpreter": {
   "hash": "2be5faf79681da6f2a61fdfdd5405d65d042280f7fba6178067603e3a2925119"
  },
  "kernelspec": {
   "display_name": "Python 3.10.2 64-bit",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.2"
  },
  "orig_nbformat": 4
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
